export const FLAG_CODES = [
    "mx", "za", "kr", "cz", "ca", "ba", "qa", "ch", "br", "ma",
    "ht", "gb-sct", "us", "py", "au", "tr", "de", "cw", "ci", "ec",
    "nl", "jp", "se", "tn", "be", "eg", "ir", "nz", "es", "cv",
    "sa", "uy", "fr", "sn", "iq", "no", "ar", "dz", "at", "jo",
    "pt", "cd", "uz", "co", "gb-eng", "hr", "gh", "pa",
]

export const COUNTRY_CODES: Record<string, string> = {
    "mexico": "MEX",
    "south africa": "RSA",
    "south korea": "KOR",
    "czech republic": "CZE",
    "canada": "CAN",
    "bosnia and herzegovina": "BIH",
    "qatar": "QAT",
    "switzerland": "SUI",
    "brazil": "BRA",
    "morocco": "MAR",
    "haiti": "HAI",
    "scotland": "SCO",
    "united states": "USA",
    "paraguay": "PAR",
    "australia": "AUS",
    "turkey": "TUR",
    "germany": "GER",
    "curacao": "CUW",
    "ivory coast": "CIV",
    "ecuador": "ECU",
    "netherlands": "NED",
    "japan": "JPN",
    "sweden": "SWE",
    "tunisia": "TUN",
    "belgium": "BEL",
    "egypt": "EGY",
    "iran": "IRN",
    "new zealand": "NZL",
    "spain": "ESP",
    "cape verde": "CPV",
    "saudi arabia": "KSA",
    "uruguay": "URU",
    "france": "FRA",
    "senegal": "SEN",
    "iraq": "IRQ",
    "norway": "NOR",
    "argentina": "ARG",
    "algeria": "ALG",
    "austria": "AUT",
    "jordan": "JOR",
    "portugal": "POR",
    "dr congo": "COD",
    "uzbekistan": "UZB",
    "colombia": "COL",
    "england": "ENG",
    "croatia": "CRO",
    "ghana": "GHA",
    "panama": "PAN",
}
