export const FLAG_CODES = [
    "mx", "za", "kr", "cz", "ca", "ba", "qa", "ch", "br", "ma",
    "ht", "gb-sct", "us", "py", "au", "tr", "de", "cw", "ci", "ec",
    "nl", "jp", "se", "tn", "be", "eg", "ir", "nz", "es", "cv",
    "sa", "uy", "fr", "sn", "iq", "no", "ar", "dz", "at", "jo",
    "pt", "cd", "uz", "co", "gb-eng", "hr", "gh", "pa",
]

export const COUNTRY_CODES: Record<string, string> = {
    "mexico": "MEX",
    "south africa": "RSA",
    "south korea": "KOR",
    "czech republic": "CZE",
    "canada": "CAN",
    "bosnia and herzegovina": "BIH",
    "qatar": "QAT",
    "switzerland": "SUI",
    "brazil": "BRA",
    "morocco": "MAR",
    "haiti": "HAI",
    "scotland": "SCO",
    "united states": "USA",
    "paraguay": "PAR",
    "australia": "AUS",
    "turkey": "TUR",
    "germany": "GER",
    "curacao": "CUW",
    "ivory coast": "CIV",
    "ecuador": "ECU",
    "netherlands": "NED",
    "japan": "JPN",
    "sweden": "SWE",
    "tunisia": "TUN",
    "belgium": "BEL",
    "egypt": "EGY",
    "iran": "IRN",
    "new zealand": "NZL",
    "spain": "ESP",
    "cape verde": "CPV",
    "saudi arabia": "KSA",
    "uruguay": "URU",
    "france": "FRA",
    "senegal": "SEN",
    "iraq": "IRQ",
    "norway": "NOR",
    "argentina": "ARG",
    "algeria": "ALG",
    "austria": "AUT",
    "jordan": "JOR",
    "portugal": "POR",
    "dr congo": "COD",
    "uzbekistan": "UZB",
    "colombia": "COL",
    "england": "ENG",
    "croatia": "CRO",
    "ghana": "GHA",
    "panama": "PAN",
}

// FIFA World Rankings (November 2025, used for seeding)
export const FIFA_RANKINGS: Record<string, number> = {
    "spain": 1,
    "argentina": 2,
    "france": 3,
    "england": 4,
    "brazil": 5,
    "portugal": 6,
    "netherlands": 7,
    "belgium": 8,
    "germany": 9,
    "croatia": 10,
    "morocco": 11,
    "colombia": 13,
    "united states": 14,
    "mexico": 15,
    "uruguay": 16,
    "switzerland": 17,
    "japan": 18,
    "senegal": 19,
    "iran": 20,
    "south korea": 22,
    "ecuador": 23,
    "austria": 24,
    "turkey": 25,
    "australia": 26,
    "canada": 27,
    "norway": 29,
    "panama": 30,
    "egypt": 34,
    "algeria": 35,
    "scotland": 36,
    "paraguay": 39,
    "tunisia": 40,
    "ivory coast": 42,
    "sweden": 43,
    "czech republic": 44,
    "uzbekistan": 50,
    "qatar": 51,
    "dr congo": 56,
    "iraq": 58,
    "saudi arabia": 60,
    "south africa": 61,
    "jordan": 66,
    "cape verde": 68,
    "bosnia and herzegovina": 71,
    "ghana": 72,
    "curacao": 82,
    "haiti": 84,
    "new zealand": 86,
}
