on: [push]

concurrency:
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: cd lambdas && ./gradlew build
      - name: Test
        run: cd lambdas && ./gradlew test

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - name: Build jar
        run: cd lambdas && ./gradlew shadowJar
      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"
          CDK_ACCOUNT_ID: ${{ secrets.CDK_ACCOUNT_ID }}
          CDK_DB_PASSWORD: ${{ secrets.CDK_DB_PASSWORD }}
